# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'benhvien-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'MBProgressHUD', '~> 1.0'
pod 'PureLayout'

end
